---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: system:talos-nodes
    labels:
        kubernetes.io/bootstrapping: rbac-defaults
    annotations:
        rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:talos-nodes
subjects:
    - kind: Group
      name: system:nodes
      apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: system:talos-nodes
    labels:
        kubernetes.io/bootstrapping: rbac-defaults
rules:
    - apiGroups:
          - discovery.k8s.io
      resources:
          - endpointslices
      verbs:
          - get
          - list
          - watch
